nginx:
    image: 'nginx'
    ports:
        - '80:80'
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public_html:/usr/share/nginx/html
    links:
        - php
php:
    image: 'php:fpm'
    volumes:
        - ./public_html:/usr/share/nginx/html
mysql:
    image: '459below/mariadb-armv7'
    ports:
        - '3306:3306'
    volumes:
        - ./database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: admin
phpmyadmin:
    image: 'martinjohn/phpmyadmin'
    restart: always
    links:
        - mysql:mysql
    ports:
        - 81:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: admin
        PMA_HOSTS: mysql

